version: '3.8'

services:
  asa-dashboard-ui:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      # Mount source code for development
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_FRONTEND_ONLY=${VITE_FRONTEND_ONLY:-false}
      - VITE_API_URL=${VITE_API_URL:-http://host.docker.internal:4000}
    ports:
      - "5173:5173"  # Vite dev server port
    command: npm run dev -- --host 0.0.0.0 